print("=== Your Adventure Simulator ===")
print("You will be asked abunch of questions then we'll make an amazing story with YOU as the star")
print()
name = input("Your name:" )
enemy = input("Your worst enemy:" )
superpower = input("Your super power:") 
print()
print("Our story begins as our hero name aproaches aforeboarding castle...")
print("Suddenly a bolt of lightining striked the ground at the feet of", name)
print("\033[31m'Our final battle begins!'\033[0m Shouts the evil", enemy, "clearly missing the fact that", name, "has the power of", superpower, "\033[35m which meas they will win quiet easily \033[0m")
