print("Getting to know you!")
print("")
name = input("Whats your name?: ")
food = input("what your favourite food: ")
music = input("Whats your favourite music? ")
country = input("Where do you live?: ")
print("")
print("You are")
print(name)
print("You are probably hungry for")
print(food)
print("and you are definately getting your groove on to")
print(music)
print("living in the amazing country")
print(country)
